name: Reusable workflow example

on:
  workflow_dispatch

jobs:
  example_job:
    runs-on : self hosted
    steps:
      - name: Use RW
        uses: aditsrin/StarterAction/.github/workflows/blank.yml@main
      - name: Welcome print
        run : echo "Hello, World!"
